FROM ubuntu:20.04

# install packages
RUN DEBIAN_FRONTEND="noninteractive" apt-get update && DEBIAN_FRONTEND="noninteractive" apt-get install -y \
    git redis-server postgresql postgresql-server-dev-all \
    libxml2-dev libxslt1-dev python-dev lib32z1-dev python3-pip supervisor nginx sudo 
# Set postgres data location to /data/db
RUN sed -i 's/\/var\/lib\/postgresql\/12\/main/\/data\/db/g' /etc/postgresql/12/main/postgresql.conf
RUN python3 -m pip install django-environ==0.7.0 redis channels_redis==3.3.0 psycopg2==2.8.6

ARG NUMBAS_LTI_REPO="https://github.com/numbas/numbas-lti-provider.git"
ARG NUMBAS_LTI_BRANCH="v3_STABLE"

# get the numbas-lti-provider code
RUN git clone --depth 1 --branch ${NUMBAS_LTI_BRANCH} ${NUMBAS_LTI_REPO} /opt/numbas-lti-provider

# set up user group
RUN adduser --disabled-password --gecos "" numbas_lti && adduser --disabled-password --gecos "" www-data numbas_lti
RUN chown -R numbas_lti:numbas_lti /opt/numbas-lti-provider

COPY files/nginx/templates/self_contained.conf.template /etc/nginx/sites-available/default
COPY files/supervisord/conf /etc/supervisor/conf.d/numbas_lti.conf
COPY files/numbas-lti-provider/settings.py /opt/numbas-lti-provider/numbasltiprovider/settings.py

RUN chown numbas_lti:numbas_lti /opt/numbas-lti-provider/numbasltiprovider/settings.py

WORKDIR /opt/numbas-lti-provider
RUN python3 -m pip install -r requirements.txt

COPY setup.sh update.sh run.sh files/numbas-lti-provider/install /tmp/

CMD bash /tmp/run.sh
